### ISSUE TITLE
indiserver1.9.7 doesn't like asynch stdout stream writer

### ISSUE THREAD

**Issue by srswinde** [MMTObservatory/pyINDI#20]
After an update to the indilib indiserver program somewhere between version 1.8.2 and 1.9.7 the way pyindi writes to stdout which is collected by indiserver started giving a connection reset error. I don't know why the stdout connection would be reset. Currently we are using an asyncio streamwriter class to send the indi lilxml to stdout. 

```
$ indiserver ./skeleton.py 
2022-08-22T18:56:32: startup: indiserver ./skeleton.py2022-08-22T18:56:42: Driver ./skeleton.py: Traceback (most recent call last):
2022-08-22T18:56:42: Driver ./skeleton.py:   File "././skeleton.py", line 116, in <module>
2022-08-22T18:56:42: Driver ./skeleton.py:     sk.start()
2022-08-22T18:56:42: Driver ./skeleton.py:   File "/home/sswindell/git-clones/pyINDI/pyindi/device.py", line 860, in start
2022-08-22T18:56:42: Driver ./skeleton.py:     self.mainloop.run_until_complete(future)
2022-08-22T18:56:42: Driver ./skeleton.py:   File "/home/sswindell/anaconda3/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
2022-08-22T18:56:42: Driver ./skeleton.py:     return future.result()
2022-08-22T18:56:42: Driver ./skeleton.py:   File "/home/sswindell/git-clones/pyINDI/pyindi/device.py", line 934, in toindiserver
2022-08-22T18:56:42: Driver ./skeleton.py:     await self.writer.drain()
2022-08-22T18:56:42: Driver ./skeleton.py:   File "/home/sswindell/anaconda3/lib/python3.7/asyncio/streams.py", line 348, in drain
2022-08-22T18:56:42: Driver ./skeleton.py:     await self._protocol._drain_helper()
2022-08-22T18:56:42: Driver ./skeleton.py:   File "/home/sswindell/anaconda3/lib/python3.7/asyncio/streams.py", line 202, in _drain_helper
2022-08-22T18:56:42: Driver ./skeleton.py:     raise ConnectionResetError('Connection lost')
2022-08-22T18:56:42: Driver ./skeleton.py: ConnectionResetError: Connection lost
```

**Comment by davner** [comment]
Can we close this issue now?
